/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cello_tablet_JTabletCursor */

#ifndef _Included_cello_tablet_JTabletCursor
#define _Included_cello_tablet_JTabletCursor
#ifdef __cplusplus
extern "C" {
#endif
#undef cello_tablet_JTabletCursor_DATA_CURSOR
#define cello_tablet_JTabletCursor_DATA_CURSOR 0L
#undef cello_tablet_JTabletCursor_DATA_BUTTONS
#define cello_tablet_JTabletCursor_DATA_BUTTONS 1L
#undef cello_tablet_JTabletCursor_DATA_X
#define cello_tablet_JTabletCursor_DATA_X 2L
#undef cello_tablet_JTabletCursor_DATA_Y
#define cello_tablet_JTabletCursor_DATA_Y 3L
#undef cello_tablet_JTabletCursor_DATA_Z
#define cello_tablet_JTabletCursor_DATA_Z 4L
#undef cello_tablet_JTabletCursor_DATA_PRESSURE
#define cello_tablet_JTabletCursor_DATA_PRESSURE 5L
#undef cello_tablet_JTabletCursor_DATA_TANGENT_PRESSURE
#define cello_tablet_JTabletCursor_DATA_TANGENT_PRESSURE 6L
#undef cello_tablet_JTabletCursor_DATA_ORIENTATION_AZIMUTH
#define cello_tablet_JTabletCursor_DATA_ORIENTATION_AZIMUTH 7L
#undef cello_tablet_JTabletCursor_DATA_ORIENTATION_ALTITUDE
#define cello_tablet_JTabletCursor_DATA_ORIENTATION_ALTITUDE 8L
#undef cello_tablet_JTabletCursor_DATA_ORIENTATION_TWIST
#define cello_tablet_JTabletCursor_DATA_ORIENTATION_TWIST 9L
#undef cello_tablet_JTabletCursor_DATA_ROTATION_PITCH
#define cello_tablet_JTabletCursor_DATA_ROTATION_PITCH 10L
#undef cello_tablet_JTabletCursor_DATA_ROTATION_ROLL
#define cello_tablet_JTabletCursor_DATA_ROTATION_ROLL 11L
#undef cello_tablet_JTabletCursor_DATA_ROTATION_YAW
#define cello_tablet_JTabletCursor_DATA_ROTATION_YAW 12L
#undef cello_tablet_JTabletCursor_DATA_ARRAY_SIZE
#define cello_tablet_JTabletCursor_DATA_ARRAY_SIZE 13L
#undef cello_tablet_JTabletCursor_TYPE_UNKNOWN
#define cello_tablet_JTabletCursor_TYPE_UNKNOWN 0L
#undef cello_tablet_JTabletCursor_TYPE_PEN_TIP
#define cello_tablet_JTabletCursor_TYPE_PEN_TIP 1L
#undef cello_tablet_JTabletCursor_TYPE_PEN_ERASER
#define cello_tablet_JTabletCursor_TYPE_PEN_ERASER 2L
#undef cello_tablet_JTabletCursor_TYPE_PUCK
#define cello_tablet_JTabletCursor_TYPE_PUCK 3L
#undef cello_tablet_JTabletCursor_TYPE_STYLUS
#define cello_tablet_JTabletCursor_TYPE_STYLUS 1L
#undef cello_tablet_JTabletCursor_TYPE_AIRBRUSH
#define cello_tablet_JTabletCursor_TYPE_AIRBRUSH 2L
#undef cello_tablet_JTabletCursor_TYPE_4DMOUSE
#define cello_tablet_JTabletCursor_TYPE_4DMOUSE 3L
#undef cello_tablet_JTabletCursor_TYPE_LENS_CURSOR
#define cello_tablet_JTabletCursor_TYPE_LENS_CURSOR 4L
/* Inaccessible static: dataMaximum */
/* Inaccessible static: dataMinimum */
/* Inaccessible static: dataIsAvailable */
/* Inaccessible static: dataSupported */
#ifdef __cplusplus
}
#endif
#endif
