testapp: test.cpp
	cl $(FLAGS) $^ -o jtablettest.exe -link WINTAB32.LIB kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib
