# makefile part of linux port 
# Linux port contributed by Ben Davis (http://bdavis.strangesoft.net/)

.PHONY: all install clean test test2

all:
	@$(MAKE) --no-print-directory -f Makefile.linux.all

install:
	cp libjtablet.so ${JAVA_HOME}/jre/lib/i386/
	cp ../dist/jtablet.jar ${JAVA_HOME}/jre/lib/ext/

clean:
	rm -f libjtablet.so *.o *.d

test:
	cd test && appletviewer JTablet-test2.html

test2:
	cd test && java -cp jtablettest.jar:lui.jar cello.tablettest.JTablettest2
