/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cello_tablet_JTablet */

#ifndef _Included_cello_tablet_JTablet
#define _Included_cello_tablet_JTablet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cello_tablet_JTablet
 * Method:    getLibraryVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cello_tablet_JTablet_getLibraryVersion
  (JNIEnv *, jclass);

/*
 * Class:     cello_tablet_JTablet
 * Method:    tabletAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cello_tablet_JTablet_tabletAvailable
  (JNIEnv *, jclass);

/*
 * Class:     cello_tablet_JTablet
 * Method:    initializeTablet
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_cello_tablet_JTablet_initializeTablet
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     cello_tablet_JTablet
 * Method:    closeTablet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cello_tablet_JTablet_closeTablet
  (JNIEnv *, jclass);

/*
 * Class:     cello_tablet_JTablet
 * Method:    pollCursor
 * Signature: (Z)Lcello/tablet/JTabletCursor;
 */
JNIEXPORT jobject JNICALL Java_cello_tablet_JTablet_pollCursor
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     cello_tablet_JTablet
 * Method:    getCursorData
 * Signature: (Lcello/tablet/JTabletCursor;I)V
 */
JNIEXPORT void JNICALL Java_cello_tablet_JTablet_getCursorData
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
